-- ============================================================================
-- Expensio · Savings goals & contributions
--
-- HOW TO APPLY: open Supabase → SQL Editor → paste this whole file → Run.
-- It is idempotent (safe to run more than once). Requires 0001–0003 first.
--
-- WHAT CHANGES
--  1. New `savings_goals` table: named jars ("Emergency fund", "Investments")
--     with an optional lifetime target and an optional planned monthly
--     allocation. Savings are NOT expenses — they never touch the expenses
--     table or the income − expenses balance.
--  2. New `savings_contributions` table: individual amounts set aside toward a
--     goal on a date. Progress, monthly funding status and growth charts are
--     all derived from these rows.
--  Both tables are personal-only for now (no group_id).
-- ============================================================================

-- ── PART A · Goals ─────────────────────────────────────────────────────────────
create table if not exists public.savings_goals (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references public.profiles(id) on delete cascade,
  name               text not null,
  target_amount      numeric check (target_amount > 0),      -- null = open-ended
  monthly_allocation numeric check (monthly_allocation > 0), -- null = no plan
  color              text not null default '#38bdf8',
  created_at         timestamptz default now()
);

create index if not exists savings_goals_user_idx on public.savings_goals(user_id);

alter table public.savings_goals enable row level security;

drop policy if exists "owner reads goals" on public.savings_goals;
create policy "owner reads goals"
  on public.savings_goals for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "owner creates goals" on public.savings_goals;
create policy "owner creates goals"
  on public.savings_goals for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "owner updates goals" on public.savings_goals;
create policy "owner updates goals"
  on public.savings_goals for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "owner deletes goals" on public.savings_goals;
create policy "owner deletes goals"
  on public.savings_goals for delete to authenticated
  using (user_id = auth.uid());

-- ── PART B · Contributions ─────────────────────────────────────────────────────
create table if not exists public.savings_contributions (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  goal_id    uuid not null references public.savings_goals(id) on delete cascade,
  amount     numeric not null check (amount > 0),
  date       date not null,
  created_at timestamptz default now()
);

create index if not exists savings_contributions_user_idx on public.savings_contributions(user_id);
create index if not exists savings_contributions_goal_idx on public.savings_contributions(goal_id);

alter table public.savings_contributions enable row level security;

drop policy if exists "owner reads contributions" on public.savings_contributions;
create policy "owner reads contributions"
  on public.savings_contributions for select to authenticated
  using (user_id = auth.uid());

-- Insert must target one of the caller's OWN goals (FK checks bypass RLS, so
-- the ownership subquery here is the real guard).
drop policy if exists "owner creates contributions" on public.savings_contributions;
create policy "owner creates contributions"
  on public.savings_contributions for insert to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.savings_goals g
      where g.id = goal_id and g.user_id = auth.uid()
    )
  );

drop policy if exists "owner deletes contributions" on public.savings_contributions;
create policy "owner deletes contributions"
  on public.savings_contributions for delete to authenticated
  using (user_id = auth.uid());
